import { useMemo, useState, useEffect } from "react";
import { MessageCircle, Send, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/lib/auth-context";
import { useQuery } from "@tanstack/react-query";
import { getBuyerOrdersApi, getBuyerProductsApi } from "@/lib/buyer-api";

type ChatRole = "user" | "bot";

interface ChatMessage {
  id: string;
  role: ChatRole;
  text: string;
}

interface TrainingData {
  intent: string;
  question: string;
  response: string;
}

const initialMessage: ChatMessage = {
  id: "welcome",
  role: "bot",
  text: "Hi! I am your MS Garments assistant. Ask about shop details, products, stock, orders, pricing, payment, or reviews!",
};

// ML-based text similarity function (TF-IDF inspired)
const calculateSimilarity = (str1: string, str2: string): number => {
  // Preprocess both strings
  const preprocess = (text: string) => {
    return text.toLowerCase()
      .trim()
      .replace(/[^a-z0-9\s]/g, '')
      .replace(/\s+/g, ' ');
  };
  
  const s1 = preprocess(str1);
  const s2 = preprocess(str2);
  
  // Exact match
  if (s1 === s2) return 1.0;
  
  // Contains match
  if (s1.includes(s2) || s2.includes(s1)) return 0.85;
  
  // Word-based similarity with improved scoring
  const words1 = s1.split(/\s+/).filter(w => w.length > 0);
  const words2 = s2.split(/\s+/).filter(w => w.length > 0);
  
  if (words1.length === 0 || words2.length === 0) return 0;
  
  let matchCount = 0;
  let partialMatchCount = 0;
  
  // Check for exact and partial word matches
  words1.forEach(word1 => {
    const exactMatch = words2.some(word2 => word1 === word2);
    const partialMatch = words2.some(word2 => 
      word1.includes(word2) || word2.includes(word1)
    );
    
    if (exactMatch) {
      matchCount += 1;
    } else if (partialMatch) {
      partialMatchCount += 0.5;
    }
  });
  
  const totalScore = matchCount + partialMatchCount;
  const similarity = totalScore / Math.max(words1.length, words2.length);
  
  return similarity;
};

const BuyerChatbot = () => {
  const { token } = useAuth();
  const [isOpen, setIsOpen] = useState(false);
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState<ChatMessage[]>([initialMessage]);
  const [trainingData, setTrainingData] = useState<TrainingData[]>([]);
  const [isTraining, setIsTraining] = useState(true);

  // Load ML-trained model (generated by Python script)
  useEffect(() => {
    const loadTrainingData = async () => {
      try {
        // Load pre-trained NLP model JSON (generated by train_simple_nlp.py)
        const response = await fetch('/chatbot_nlp_model.json');
        const data: TrainingData[] = await response.json();
        
        setTrainingData(data);
        setIsTraining(false);
        console.log(`✅ Chatbot loaded with ${data.length} NLP-trained examples`);
        console.log(`📊 Trained using Python NLP (480 features)`);
        console.log(`🔧 Features: Lemmatization, Synonym Expansion, Intent Classification`);
      } catch (error) {
        console.error('Failed to load trained model:', error);
        setIsTraining(false);
      }
    };

    loadTrainingData();
  }, []);

  const { data: ordersData } = useQuery({
    queryKey: ["buyer-orders-chatbot"],
    queryFn: () => getBuyerOrdersApi(token ?? ""),
    enabled: !!token,
  });

  const { data: productsData } = useQuery({
    queryKey: ["buyer-products-chatbot"],
    queryFn: () => getBuyerProductsApi(token ?? ""),
    enabled: !!token,
  });

  const orders = ordersData?.orders ?? [];
  const products = productsData?.products ?? [];

  const quickPrompts = useMemo(
    () => [
      "Hello",
      "What products available",
      "Tell me about MS Garments",
      "Cotton leggings stock",
    ],
    [],
  );

  const createBotReply = (rawQuestion: string): string => {
    const question = rawQuestion.toLowerCase();

    // Detect casual language style
    const isCasual = question.includes("machan") || question.includes("bro") || 
                     question.includes("da") || question.includes("dude");

    // PRIORITY 1: Check if asking about products/stock - show real-time data first
    const isProductQuery = question.includes("product") || question.includes("item") || 
                           question.includes("legging") || question.includes("cotton") || 
                           question.includes("stock") || question.includes("available") || 
                           question.includes("quantity") || question.includes("sell") ||
                           question.includes("what do you have") || question.includes("what you got") ||
                           question.includes("iruku") || question.includes("enna");

    if (isProductQuery && products.length > 0) {
      // Check if asking about specific product
      const productKeywords = ["legging", "cotton", "ankle", "churidar"];
      const matchedProduct = products.find(p => 
        productKeywords.some(keyword => 
          question.includes(keyword) && p.name.toLowerCase().includes(keyword)
        )
      );

      if (matchedProduct) {
        const stockStatus = matchedProduct.stock > 100 ? 
          (isCasual ? 'Good stock iruku da!' : 'In good stock!') : 
          matchedProduct.stock > 0 ? 
          (isCasual ? 'Limited stock dha machan.' : 'Limited stock.') : 
          (isCasual ? 'Out of stock da.' : 'Out of stock.');
        
        if (isCasual) {
          return `${matchedProduct.name} - Stock: ${matchedProduct.stock} units iruku da. Price: ₹${matchedProduct.wholesalePrice} per piece. ${stockStatus}`;
        }
        return `${matchedProduct.name} - Stock: ${matchedProduct.stock} units available. Price: ₹${matchedProduct.wholesalePrice} per piece. ${stockStatus}`;
      }

      // General product listing with real-time stock
      if (question.includes("what") || question.includes("show") || question.includes("available") || 
          question.includes("product") || question.includes("enna") || question.includes("iruku")) {
        const productList = products.map(p => 
          `${p.name} (Stock: ${p.stock} units, Price: ₹${p.wholesalePrice})`
        ).join(" | ");
        
        if (isCasual) {
          return `${isCasual ? 'Machan,' : ''} Available products now: ${productList}${isCasual ? ' da!' : ''}`;
        }
        return `Available products now: ${productList}`;
      }
    }

    // PRIORITY 2: Try ML-based matching with training data
    if (trainingData.length > 0) {
      let bestMatch: TrainingData | null = null;
      let bestScore = 0;

      trainingData.forEach(data => {
        const score = calculateSimilarity(question, data.question);
        if (score > bestScore) {
          bestScore = score;
          bestMatch = data;
        }
      });

      // If we found a good match (similarity > 0.25), use it
      // BUT skip generic product_inquiry responses in favor of real-time data
      if (bestMatch && bestScore > 0.25) {
        const isGenericProductResponse = bestMatch.intent.includes("product_inquiry") && 
                                        (bestMatch.response.includes("products section") || 
                                         bestMatch.response.includes("products page"));
        
        if (!isGenericProductResponse) {
          console.log(`🤖 ML Match: "${rawQuestion}" → "${bestMatch.question}" (score: ${bestScore.toFixed(2)}, intent: ${bestMatch.intent})`);
          return bestMatch.response;
        }
      }
    }

    // Real-time product stock and details (fallback)
    if (question.includes("stock") || question.includes("available") || question.includes("quantity")) {
      // Check if asking about specific product
      const productKeywords = ["legging", "cotton", "ankle", "churidar"];
      const matchedProduct = products.find(p => 
        productKeywords.some(keyword => 
          question.includes(keyword) && p.name.toLowerCase().includes(keyword)
        )
      );

      if (matchedProduct) {
        return `${matchedProduct.name} - Stock: ${matchedProduct.stock} units available. Price: ₹${matchedProduct.wholesalePrice} per piece. ${matchedProduct.stock > 100 ? 'In good stock!' : matchedProduct.stock > 0 ? 'Limited stock.' : 'Out of stock.'}`;
      }

      // General stock info
      const inStock = products.filter(p => p.stock > 0);
      const totalStock = products.reduce((sum, p) => sum + p.stock, 0);
      return `We have ${inStock.length} products in stock with total ${totalStock} units available. Ask about specific products like "cotton leggings stock" for details.`;
    }

    // Product details query
    if ((question.includes("detail") || question.includes("info") || question.includes("about")) && 
        (question.includes("product") || question.includes("legging"))) {
      if (products.length > 0) {
        const topProducts = products.slice(0, 3).map(p => 
          `${p.name} (Stock: ${p.stock}, Price: ₹${p.wholesalePrice})`
        ).join(", ");
        return `Available products: ${topProducts}. Ask about specific product stock or details.`;
      }
      return "No products currently available. Please check back later.";
    }

    // Price query for specific product
    if (question.includes("price") || question.includes("cost")) {
      const productKeywords = ["legging", "cotton", "ankle", "churidar"];
      const matchedProduct = products.find(p => 
        productKeywords.some(keyword => 
          question.includes(keyword) && p.name.toLowerCase().includes(keyword)
        )
      );

      if (matchedProduct) {
        return `${matchedProduct.name} is priced at ₹${matchedProduct.wholesalePrice} per piece. Current stock: ${matchedProduct.stock} units.`;
      }
    }

    // Fallback to rule-based responses for dynamic data
    if (question.includes("latest order") || question.includes("recent order") || (question.includes("my") && question.includes("order"))) {
      const latest = orders[0];
      if (!latest) {
        return "You do not have orders yet. Open Browse Catalog and place your first order.";
      }

      return `Your latest order is ${latest.orderId} (${latest.status}). Total: INR ${latest.total.toLocaleString()}.`;
    }

    if (question.includes("how many") && (question.includes("product") || question.includes("catalog"))) {
      const inStock = products.filter(p => p.stock > 0).length;
      return `There are ${products.length} products in catalog (${inStock} in stock right now).`;
    }

    return "I can help with orders, products, pricing, delivery, and payment methods. Try asking something or use the quick prompts below!";
  };

  const sendMessage = (text: string) => {
    const trimmed = text.trim();
    if (!trimmed) return;

    const userMessage: ChatMessage = {
      id: `user-${Date.now()}`,
      role: "user",
      text: trimmed,
    };

    const botMessage: ChatMessage = {
      id: `bot-${Date.now()}`,
      role: "bot",
      text: createBotReply(trimmed),
    };

    setMessages((previous) => [...previous, userMessage, botMessage]);
    setInput("");
  };

  return (
    <div className="fixed bottom-5 right-5 z-50">
      {isOpen && (
        <div className="mb-3 w-[22rem] max-w-[90vw] rounded-xl border border-border bg-card shadow-2xl overflow-hidden">
          <div className="flex items-center justify-between px-4 py-3 border-b border-border bg-muted/40">
            <p className="text-sm font-semibold">🤖 ML Buyer Assistant</p>
            <button onClick={() => setIsOpen(false)} className="text-muted-foreground hover:text-foreground" aria-label="Close chatbot">
              <X className="w-4 h-4" />
            </button>
          </div>

          <div className="max-h-80 overflow-y-auto p-3 space-y-2">
            {messages.map((message) => (
              <div key={message.id} className={`text-sm rounded-lg px-3 py-2 ${message.role === "user" ? "bg-primary text-primary-foreground ml-8" : "bg-muted mr-8"}`}>
                {message.text}
              </div>
            ))}
          </div>

          <div className="px-3 pb-2 flex flex-wrap gap-2">
            {quickPrompts.map((prompt) => (
              <button
                key={prompt}
                onClick={() => sendMessage(prompt)}
                className="text-[11px] px-2 py-1 rounded-full bg-secondary hover:bg-secondary/80 text-secondary-foreground"
              >
                {prompt}
              </button>
            ))}
          </div>

          <div className="p-3 border-t border-border flex items-center gap-2">
            <Input
              value={input}
              onChange={(event) => setInput(event.target.value)}
              onKeyDown={(event) => {
                if (event.key === "Enter") {
                  event.preventDefault();
                  sendMessage(input);
                }
              }}
              placeholder="Ask ML assistant..."
              className="h-9"
            />
            <Button size="sm" onClick={() => sendMessage(input)}>
              <Send className="w-4 h-4" />
            </Button>
          </div>
        </div>
      )}

      <Button onClick={() => setIsOpen((prev) => !prev)} className="h-12 w-12 rounded-full p-0 shadow-lg" aria-label="Toggle buyer chatbot">
        <MessageCircle className="w-5 h-5" />
      </Button>
    </div>
  );
};

export default BuyerChatbot;
